name: "Run lab test: single"

on:
  workflow_dispatch:
    inputs:
      subfolder:
        description: "The subfolder to enter before running the test"
        required: true
        type: choice
        options:
          - kvraft
          - raft
      testcase:
        description: "Testcase name"
        required: true
        type: choice
        options:
          - All
          - 3A
          - TestFigure8Unreliable2C
          - TestBackup2B
      round:
        description: "# rounds to run the test"
        required: true
        type: choice
        default: "2"
        options:
          - "1"
          - "2"
          - "5"
          - "10"
          - "20"
          - "50"
          - "75"
          - "100"
          - "125"
          - "150"
          - "175"
          - "200"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run ${{ github.event.inputs.testcase }} for ${{ github.event.inputs.round }} rounds
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.15

      - name: Run tests
        shell: bash
        run: |
          # https://stackoverflow.com/a/78924711
          set +e
          cd src/${{ github.event.inputs.subfolder }}
          for i in {1..${{ github.event.inputs.round }}}
          do
            echo "Round $i:"
            rm -f app.log

            if [ "${{ github.event.inputs.testcase }}" = "All" ]; then
              time go test -race
            else
              time go test -run ${{ github.event.inputs.testcase }} -race
            fi

            ret=$?
            echo "Max goroutine num during execution: `sort -nr goroutine_num_xxafbnlassfb.log | head -n 1`"
            if [ $ret -ne 0 ]; then
              echo "Test failed in round $i. Exiting loop."
              exit 1123
            fi
            sleep 1
          done
          echo "Test succeeds"